"""initial schema

Revision ID: d77775e8f51b
Revises:
Create Date: 2026-09-21 00:58:40.979365

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "d77775e8f51b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "venue",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("minutes_per_position", mysql.TINYINT(unsigned=True), server_default=sa.text("4"), nullable=False),
        sa.Column("hold_minutes", mysql.TINYINT(unsigned=True), server_default=sa.text("10"), nullable=False),
        sa.Column("paused", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("created_at", mysql.DATETIME(fsp=6), server_default=sa.text("(UTC_TIMESTAMP(6))"), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(fsp=6), server_default=sa.text("(UTC_TIMESTAMP(6))"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_venue")),
        sa.UniqueConstraint("slug", name=op.f("uq_venue_slug")),
    )
    op.create_table(
        "queue_entry",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("venue_id", sa.BigInteger(), nullable=False),
        sa.Column("public_token", sa.String(length=64), nullable=False),
        sa.Column("service_date", sa.Date(), nullable=False),
        sa.Column("ticket", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("phone_e164", sa.String(length=16), nullable=False),
        sa.Column("party_size", mysql.TINYINT(unsigned=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "waiting",
                "called",
                "seated",
                "cancelled",
                "no_show",
                "removed",
                name="entrystatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "active_phone_key",
            sa.String(length=16),
            sa.Computed("IF(status IN ('waiting', 'called'), phone_e164, NULL)", persisted=True),
            nullable=True,
        ),
        sa.Column("consent_accepted_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("consent_text_version", sa.String(length=16), nullable=False),
        sa.Column("joined_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("called_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("on_the_way_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("ended_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=6), server_default=sa.text("(UTC_TIMESTAMP(6))"), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(fsp=6), server_default=sa.text("(UTC_TIMESTAMP(6))"), nullable=False),
        sa.CheckConstraint("party_size BETWEEN 1 AND 20", name=op.f("ck_queue_entry_party_size_range")),
        sa.ForeignKeyConstraint(["venue_id"], ["venue.id"], name=op.f("fk_queue_entry_venue_id_venue")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_queue_entry")),
        sa.UniqueConstraint("public_token", name=op.f("uq_queue_entry_public_token")),
        sa.UniqueConstraint("venue_id", "active_phone_key", name="uq_queue_entry_venue_active_phone"),
        sa.UniqueConstraint("venue_id", "service_date", "ticket", name="uq_queue_entry_venue_service_ticket"),
    )
    op.create_index(
        "ix_queue_entry_venue_status_joined", "queue_entry", ["venue_id", "status", "joined_at"], unique=False
    )
    op.create_index("ix_queue_entry_venue_ticket", "queue_entry", ["venue_id", "ticket"], unique=False)
    op.create_table(
        "service_day_counter",
        sa.Column("venue_id", sa.BigInteger(), nullable=False),
        sa.Column("service_date", sa.Date(), nullable=False),
        sa.Column("last_ticket", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["venue_id"], ["venue.id"], name=op.f("fk_service_day_counter_venue_id_venue")),
        sa.PrimaryKeyConstraint("venue_id", "service_date", name=op.f("pk_service_day_counter")),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("venue_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column("last_login_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=6), server_default=sa.text("(UTC_TIMESTAMP(6))"), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(fsp=6), server_default=sa.text("(UTC_TIMESTAMP(6))"), nullable=False),
        sa.ForeignKeyConstraint(["venue_id"], ["venue.id"], name=op.f("fk_user_venue_id_venue")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
        sa.UniqueConstraint("username", name=op.f("uq_user_username")),
    )
    op.create_table(
        "venue_schedule",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("venue_id", sa.BigInteger(), nullable=False),
        sa.Column("weekday", mysql.TINYINT(unsigned=True), nullable=False),
        sa.Column("is_open", sa.Boolean(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.CheckConstraint(
            "NOT is_open OR start_time <> end_time", name=op.f("ck_venue_schedule_start_differs_from_end_when_open")
        ),
        sa.CheckConstraint("weekday BETWEEN 0 AND 6", name=op.f("ck_venue_schedule_weekday_range")),
        sa.ForeignKeyConstraint(
            ["venue_id"], ["venue.id"], name=op.f("fk_venue_schedule_venue_id_venue"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_venue_schedule")),
        sa.UniqueConstraint("venue_id", "weekday", name="uq_venue_schedule_venue_weekday"),
    )
    op.create_table(
        "auth",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("token_hash", sa.CHAR(length=64), nullable=False),
        sa.Column("device_label", sa.String(length=255), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("last_used_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("revoked_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name=op.f("fk_auth_user_id_user"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_auth_token_hash")),
    )
    op.create_table(
        "entry_event",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("entry_id", sa.BigInteger(), nullable=False),
        sa.Column("venue_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "event_type",
            sa.Enum(
                "joined",
                "called",
                "seated",
                "no_show",
                "cancelled",
                "removed",
                "on_the_way",
                name="eventtype",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "from_status",
            sa.Enum(
                "waiting",
                "called",
                "seated",
                "cancelled",
                "no_show",
                "removed",
                name="entrystatus",
                native_enum=False,
                length=16,
            ),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            sa.Enum(
                "waiting",
                "called",
                "seated",
                "cancelled",
                "no_show",
                "removed",
                name="entrystatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("actor", sa.Enum("diner", "host", name="actor", native_enum=False, length=16), nullable=False),
        sa.Column("occurred_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.ForeignKeyConstraint(["entry_id"], ["queue_entry.id"], name=op.f("fk_entry_event_entry_id_queue_entry")),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name=op.f("fk_entry_event_user_id_user")),
        sa.ForeignKeyConstraint(["venue_id"], ["venue.id"], name=op.f("fk_entry_event_venue_id_venue")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entry_event")),
    )
    op.create_index("ix_entry_event_entry_occurred", "entry_event", ["entry_id", "occurred_at"], unique=False)
    op.create_index("ix_entry_event_venue_occurred", "entry_event", ["venue_id", "occurred_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_entry_event_venue_occurred", table_name="entry_event")
    op.drop_index("ix_entry_event_entry_occurred", table_name="entry_event")
    op.drop_table("entry_event")
    op.drop_table("auth")
    op.drop_table("venue_schedule")
    op.drop_table("user")
    op.drop_table("service_day_counter")
    op.drop_index("ix_queue_entry_venue_ticket", table_name="queue_entry")
    op.drop_index("ix_queue_entry_venue_status_joined", table_name="queue_entry")
    op.drop_table("queue_entry")
    op.drop_table("venue")
    # ### end Alembic commands ###
